#!/bin/sh

set -e

EDBP_VERSION="$(cat ../VERSION 2>/dev/null || cat VERSION)"

lb config noauto \
    --distribution trixie \
    --architecture amd64 \
    --archive-areas "main contrib non-free-firmware" \
    --debian-installer live \
    --debian-installer-gui true \
    --iso-application "EDBP Enterprise Desktop" \
    --iso-publisher "Enterprise IT Department" \
    --iso-volume "EDBP_${EDBP_VERSION}" \
    --bootappend-live "boot=live components quiet splash" \
    --bootappend-install "auto=true priority=critical vga=788 file=/cdrom/preseed.cfg quiet" \
    "${@}"
